### ISSUE TITLE
Make permission slug to be unique?

### ISSUE THREAD

**Issue by rakk7** [jungessolutions/laravel-acl#109]
I am not sure if this is a bug.. but shouldn't be the permissions's slugs to be a unique? same as groups..

https://github.com/jungessolutions/laravel-acl/blob/513ef3adb3a615d30613c55a41911e0a563922cc/src/database/migrations/2019_03_16_005237_create_permissions_table.php#L20

**Comment by mateusjunges** [comment]
Yeah it should be unique.
Think I made a mistake while removing the `->billable(false)` from the description field.
You can send a pull request if you feels comfortable or I'll fix it in about 1 hour.

Thanks @rakk7 !

**Comment by mateusjunges** [comment]
@rakk7 fixed with #110
