### ISSUE TITLE
Eager loading Permissions & Groups

### ISSUE THREAD

**Issue by ACvijic** [jungessolutions/laravel-acl#112]
### Issue:
When checking for permissions via blade directives, each check results in a new DB query. Granted, these queries take between 200 & 500 μs, but consider the following use-case:
I have a sidebar. For each link in that sidebar, I want to check user permissions. How many links I have there equals to how many queries I'll have when rendering each page.

### Sugestions:
I tried eager loading `permissions` and `groups.permissions`, then I checked the code and figured out that that didn't matter. The `hasPermission()` makes a new DB query anyway. 
It would be great if the `Junges\ACL\Traits\UsersTrait` could be changed to use eager-loaded relations, instead of making new queries. 
The other solution would be to register a singleton via your service provider, which would query the database at least two times, to load all Permissions & Groups.

**Comment by mateusjunges** [comment]
Hi @ACvijic ,
You mean somenthing like cached permissions?

**Comment by ACvijic** [comment]
Yes, something like that. I called the feature request "eager loading" because the first thing that came to mind as a possible solution was Laravel's [eager loading concept](https://laravel.com/docs/5.8/eloquent-relationships#eager-loading).

**Comment by mateusjunges** [comment]
I'll spent some time thinking about it this week. 
First thing that come to my mind is to load the permissions and groups to the `User` model, and modify the `hasPermission` function to look at the eager loaded permissions instead of the database.
If you have some idea, feel free to send a PR with your implementation.

**Comment by ACvijic** [comment]
Thanks for taking the time to think about this! :slightly_smiling_face: 
I'll try and make a PR by tomorrow.

**Comment by ACvijic** [comment]
#114 
I'm a bit late, but I think I've cracked it! :sweat_smile:

**Comment by mateusjunges** [comment]
Fixed with #114
